### ISSUE TITLE
Error: Server Unavailable. 21

### ISSUE THREAD

**Issue by bgramaje** [agsh/yapople#23]
Hi, I am getting this error, is it due to my mail server is unavailable or is it a problem with the library connection?

Thanks 

(node:15288) UnhandledPromiseRejectionWarning: Error: Server Unavailable. 21
    at Client.onData (D:\00_PROYECTOS\03_raul\02_app\server\node_modules\yapople\lib\yapople.js:105:19)
    at TLSSocket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:284:9)
    at TLSSocket.Readable.push (_stream_readable.js:223:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:15288) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:15288) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by agsh** [comment]
@boralbgra Hi! This is a server error.
